Skip to content
ddasports
ddasports-app-adm-printvisitor-DSC17_V56425376765
Repository navigation
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
Update receipt date in index.html
Update receipt date in index.html #4
All jobs
Run details
Workflow file for this run
.github/workflows/main.yml at 5ffb2b3
name: Update receipt date in index.html

on:
  schedule:
    - cron: '00 00 * * *'   # 12:00 AM IST
  workflow_dispatch:
permissions:
  contents: write
  
jobs:
  generate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate index.html from template
        run: |
          # Date formats
          DATE_READABLE=$(date +"%d %b %Y")
          echo "DATE_READABLE=$DATE_READABLE" >> $GITHUB_ENV
          DATE_URL_ENCODED=$(date +"%d%%20%b%%20%Y")
          # Recreate index.html from template
          cp place_holder.html index.html
          # Replace placeholders
          sed -i "s/DATE_PLACEHOLDER_SPACE/$DATE_URL_ENCODED/g" index.html
          sed -i "s/DATE_PLACEHOLDER/$DATE_READABLE/g" index.html
      - name: Commit updated index.html
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add index.html
          git commit -m "chore: update receipt date to $DATE_READABLE" || exit 0
          git push
          
      - name: Send receipt on Telegram
        run: |
          MESSAGE="Visitor Receipt
      
          Complex Name - Dwarka Sports Complex Sector 17
          Receipt Date - $DATE_READABLE
          Receipt Type - Casual
          Receipt - DSC17_V56425376765
          Membership No. - NA
          Player Name - HARSH
          Facility - Badminton Indoor
          Fee - 100.00
          Transaction Type - QR Code
          User/Time - recp3 / 5:10 PM
      
          Note:
          Once the receipt is issued, money will not be refunded.
          The management accepts no responsibility for any accident or mishap.
          Any injuries / infections / loss of life while availing the facilities
          will be at the member/user's risk.
          No compensation or claim shall be entertained.
      
          Best Regards,
          DDA / DSC17
      
          <a href='https://ddasports.github.io/app-adm-printvisitor-DSC17_V56425265654/'>Verify Receipt</a>"
      
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TG_CHAT_ID }} \
            -d text="$MESSAGE"
